wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.15
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1754984212
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 12
      - 41
      - 51
      - 55
      3:
      - 13
      - 23
      4: 3.10.15
      5: 0.17.2
      8:
      - 4
      - 5
      13: darwin-arm64
